name:                VRML
version:             0.1.0.0
github:              "junjihashimoto/VRML"
license:             MIT
author:              "Junji Hashimoto"
maintainer:          "junji.hashimoto@gmail.com"
extra-source-files:
- README.md
- ChangeLog.md

synopsis:            VRML parser and generator for Haskell
category:            Graphics

description:         Please see the README on GitHub at https://github.com/junjihashimoto/VRML#readme

dependencies:
- base >= 4.7 && < 5
- megaparsec
- text
- prettyprinter
- aeson

library:
  source-dirs: src

executables:
  vrml2haskell:
    main:                vrml2haskell.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - VRML
    - pretty-simple >= 3.0.0.0
  vrmlfmt:
    main:                vrmlfmt.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - VRML
  vrmlproto2haskell:
    main:                vrmlproto2haskell.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - VRML

tests:
  doctest:
    main:                doctests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - VRML
    - doctest
